package app.cclauncher.settings

import android.content.Context
import app.cclauncher.R
import io.github.mlmgames.settings.core.resources.AndroidStringResourceProvider
import io.github.mlmgames.settings.core.resources.StringResourceProvider

/**
 * Maps [CClauncherSettingsKeys] to Android resources.
 *
 * The settings screen reads its labels straight off the schema, so before this the
 * annotation literals were the only text it had. It now resolves them here.
 */
private val settingsResources: Map<String, Int> = mapOf(
    CClauncherSettingsKeys.CATEGORY_GENERAL to R.string.category_general,
    CClauncherSettingsKeys.CATEGORY_APPEARANCE to R.string.category_appearance,
    CClauncherSettingsKeys.CATEGORY_LAYOUT to R.string.category_layout,
    CClauncherSettingsKeys.CATEGORY_GESTURES to R.string.category_gestures,
    CClauncherSettingsKeys.CATEGORY_SYSTEM to R.string.category_system,
    CClauncherSettingsKeys.SETTING_APP_DRAWER_RESULTS_ALIGNMENT to R.string.setting_app_drawer_results_alignment,
    CClauncherSettingsKeys.SETTING_AUTO_OPEN_SINGLE_MATCHES to R.string.setting_auto_open_single_matches,
    CClauncherSettingsKeys.SETTING_AUTO_SHOW_KEYBOARD to R.string.setting_auto_show_keyboard,
    CClauncherSettingsKeys.SETTING_AUTO_UPDATE_WALLPAPER to R.string.setting_auto_update_wallpaper,
    CClauncherSettingsKeys.SETTING_CUSTOM_FONT to R.string.setting_custom_font,
    CClauncherSettingsKeys.SETTING_DEFAULT_SCREEN to R.string.setting_default_screen,
    CClauncherSettingsKeys.SETTING_DOUBLE_TAP_TO_LOCK_SCREEN to R.string.setting_double_tap_to_lock_screen,
    CClauncherSettingsKeys.SETTING_FONT_WEIGHT to R.string.setting_font_weight,
    CClauncherSettingsKeys.SETTING_GESTURE_SENSITIVITY to R.string.setting_gesture_sensitivity,
    CClauncherSettingsKeys.SETTING_HOME_APP_LABEL_ALIGNMENT to R.string.setting_home_app_label_alignment,
    CClauncherSettingsKeys.SETTING_HOME_SCREEN_COLUMNS to R.string.setting_home_screen_columns,
    CClauncherSettingsKeys.SETTING_HOME_SCREEN_PAGES to R.string.setting_home_screen_pages,
    CClauncherSettingsKeys.SETTING_HOME_SCREEN_ROWS to R.string.setting_home_screen_rows,
    CClauncherSettingsKeys.SETTING_HOME_TEXT_SIZE to R.string.setting_home_text_size,
    CClauncherSettingsKeys.SETTING_ICON_CORNER_RADIUS to R.string.setting_icon_corner_radius,
    CClauncherSettingsKeys.SETTING_ICON_PACK to R.string.setting_icon_pack,
    CClauncherSettingsKeys.SETTING_ITEM_SPACING to R.string.setting_item_spacing,
    CClauncherSettingsKeys.SETTING_LEFT_SWIPE_APP to R.string.setting_left_swipe_app,
    CClauncherSettingsKeys.SETTING_LONG_PRESS_IN_APP_DRAWER to R.string.setting_long_press_in_app_drawer,
    CClauncherSettingsKeys.SETTING_RETURN_TO_HOME_AFTER_APP to R.string.setting_return_to_home_after_app,
    CClauncherSettingsKeys.SETTING_REVERSE_SEARCH_RESULTS to R.string.setting_reverse_search_results,
    CClauncherSettingsKeys.SETTING_RIGHT_SWIPE_APP to R.string.setting_right_swipe_app,
    CClauncherSettingsKeys.SETTING_SCALE_HOME_APPS to R.string.setting_scale_home_apps,
    CClauncherSettingsKeys.SETTING_SCREEN_ORIENTATION to R.string.setting_screen_orientation,
    CClauncherSettingsKeys.SETTING_SEARCH_ALIASES to R.string.setting_search_aliases,
    CClauncherSettingsKeys.SETTING_SEARCH_BAR_POSITION to R.string.setting_search_bar_position,
    CClauncherSettingsKeys.SETTING_SEARCH_RESULTS_FONT_SIZE to R.string.setting_search_results_font_size,
    CClauncherSettingsKeys.SETTING_SEARCH_RESULTS_USE_HOME_FONT_SIZE to R.string.setting_search_results_use_home_font_size,
    CClauncherSettingsKeys.SETTING_SEARCH_SORT_ORDER to R.string.setting_search_sort_order,
    CClauncherSettingsKeys.SETTING_SEARCH_TYPE to R.string.setting_search_type,
    CClauncherSettingsKeys.SETTING_SET_PLAIN_WALLPAPER to R.string.setting_set_plain_wallpaper,
    CClauncherSettingsKeys.SETTING_SHOW_APP_DRAWER_ICONS to R.string.setting_show_app_drawer_icons,
    CClauncherSettingsKeys.SETTING_SHOW_APP_ICONS_IN_LANDSCAPE to R.string.setting_show_app_icons_in_landscape,
    CClauncherSettingsKeys.SETTING_SHOW_APP_ICONS_IN_PORTRAIT to R.string.setting_show_app_icons_in_portrait,
    CClauncherSettingsKeys.SETTING_SHOW_APP_ICONS_ON_HOME_SCREEN to R.string.setting_show_app_icons_on_home_screen,
    CClauncherSettingsKeys.SETTING_SHOW_APP_NAMES to R.string.setting_show_app_names,
    CClauncherSettingsKeys.SETTING_SHOW_HIDDEN_IN_SEARCH to R.string.setting_show_hidden_in_search,
    CClauncherSettingsKeys.SETTING_SHOW_NAMES_IN_SEARCH_AFTER to R.string.setting_show_names_in_search_after,
    CClauncherSettingsKeys.SETTING_SHOW_PAGE_INDICATOR to R.string.setting_show_page_indicator,
    CClauncherSettingsKeys.SETTING_SHOW_PINNED_SHORTCUTS to R.string.setting_show_pinned_shortcuts,
    CClauncherSettingsKeys.SETTING_SHOW_STATUS_BAR to R.string.setting_show_status_bar,
    CClauncherSettingsKeys.SETTING_SHOW_WEB_SEARCH_OPTION to R.string.setting_show_web_search_option,
    CClauncherSettingsKeys.SETTING_SWIPE_DOWN_ACTION to R.string.setting_swipe_down_action,
    CClauncherSettingsKeys.SETTING_SWIPE_DOWN_APP to R.string.setting_swipe_down_app,
    CClauncherSettingsKeys.SETTING_SWIPE_LEFT_ACTION to R.string.setting_swipe_left_action,
    CClauncherSettingsKeys.SETTING_SWIPE_RIGHT_ACTION to R.string.setting_swipe_right_action,
    CClauncherSettingsKeys.SETTING_SWIPE_UP_ACTION to R.string.setting_swipe_up_action,
    CClauncherSettingsKeys.SETTING_SWIPE_UP_APP to R.string.setting_swipe_up_app,
    CClauncherSettingsKeys.SETTING_TAP_TO_OPEN_IN_APP_DRAWER to R.string.setting_tap_to_open_in_app_drawer,
    CClauncherSettingsKeys.SETTING_TEXT_COLOR to R.string.setting_text_color,
    CClauncherSettingsKeys.SETTING_THEME to R.string.setting_theme,
    CClauncherSettingsKeys.SETTING_USE_CUSTOM_TEXT_COLOR to R.string.setting_use_custom_text_color,
    CClauncherSettingsKeys.SETTING_USE_DYNAMIC_THEME to R.string.setting_use_dynamic_theme,
    CClauncherSettingsKeys.SETTING_USE_SYSTEM_FONT to R.string.setting_use_system_font,
    CClauncherSettingsKeys.SETTING_ADJUST_HOW_EASILY_SWIPE_GESTURES_ARE_TRIGGERED_DESC to R.string.setting_adjust_how_easily_swipe_gestures_are_triggered_desc,
    CClauncherSettingsKeys.SETTING_ALIGN_APP_NAMES_ON_THE_HOME_SCREEN_DESC to R.string.setting_align_app_names_on_the_home_screen_desc,
    CClauncherSettingsKeys.SETTING_AUTOMATICALLY_UPDATE_PLAIN_WALLPAPER_WHEN_SYSTEM_THEME_CHANGES_DESC to R.string.setting_automatically_update_plain_wallpaper_when_system_theme_changes_desc,
    CClauncherSettingsKeys.SETTING_CHOOSE_CUSTOM_ICON_PACK_FOR_APPS_DESC to R.string.setting_choose_custom_icon_pack_for_apps_desc,
    CClauncherSettingsKeys.SETTING_CHOOSE_WHICH_SCREEN_TO_SHOW_WHEN_OPENING_THE_LAUNCHER_DESC to R.string.setting_choose_which_screen_to_show_when_opening_the_launcher_desc,
    CClauncherSettingsKeys.SETTING_CUSTOMIZE_TEXT_COLOR_FOR_BETTER_VISIBILITY_DESC to R.string.setting_customize_text_color_for_better_visibility_desc,
    CClauncherSettingsKeys.SETTING_DISPLAY_APP_ICONS_ON_THE_HOME_SCREEN_DESC to R.string.setting_display_app_icons_on_the_home_screen_desc,
    CClauncherSettingsKeys.SETTING_DISPLAY_PINNED_APP_SHORTCUTS_IN_THE_APP_DRAWER_DESC to R.string.setting_display_pinned_app_shortcuts_in_the_app_drawer_desc,
    CClauncherSettingsKeys.SETTING_DISPLAY_RESULTS_BOTTOM_TO_TOP_DESC to R.string.setting_display_results_bottom_to_top_desc,
    CClauncherSettingsKeys.SETTING_HORIZONTAL_ALIGNMENT_OF_APP_NAMES_IN_APP_DRAWER_RESULTS_DESC to R.string.setting_horizontal_alignment_of_app_names_in_app_drawer_results_desc,
    CClauncherSettingsKeys.SETTING_LONG_PRESS_ON_APPS_SHOWS_OPTIONS_MENU_DESC to R.string.setting_long_press_on_apps_shows_options_menu_desc,
    CClauncherSettingsKeys.SETTING_MATCH_APP_NAMES_ACROSS_TRANSLITERATIONS_AND_KEYBOARD_LAYOUTS_E_G_AFRIKA_MAY_SLIGHTLY_INCREASE_CPU_USE_ON_OLDER_DEVICES_DESC to R.string.setting_match_app_names_across_transliterations_and_keyboard_layouts_e_g_afrika_may_slightly_increase_cpu_use_on_older_devices_desc,
    CClauncherSettingsKeys.SETTING_NUMBER_OF_COLUMNS_IN_THE_HOME_SCREEN_GRID_DESC to R.string.setting_number_of_columns_in_the_home_screen_grid_desc,
    CClauncherSettingsKeys.SETTING_NUMBER_OF_HOME_SCREEN_PAGES_DESC to R.string.setting_number_of_home_screen_pages_desc,
    CClauncherSettingsKeys.SETTING_NUMBER_OF_ROWS_IN_THE_HOME_SCREEN_GRID_DESC to R.string.setting_number_of_rows_in_the_home_screen_grid_desc,
    CClauncherSettingsKeys.SETTING_OVERRIDE_THEME_TEXT_COLOR_WITH_CUSTOM_COLOR_DESC to R.string.setting_override_theme_text_color_with_custom_color_desc,
    CClauncherSettingsKeys.SETTING_POSITION_OF_THE_SEARCH_BAR_IN_THE_APP_DRAWER_DESC to R.string.setting_position_of_the_search_bar_in_the_app_drawer_desc,
    CClauncherSettingsKeys.SETTING_RETURN_TO_HOME_SCREEN_INSTEAD_OF_SEARCH_AFTER_CLOSING_AN_APP_DESC to R.string.setting_return_to_home_screen_instead_of_search_after_closing_an_app_desc,
    CClauncherSettingsKeys.SETTING_SELECT_A_CUSTOM_FONT_FILE_DESC to R.string.setting_select_a_custom_font_file_desc,
    CClauncherSettingsKeys.SETTING_SET_A_PLAIN_BLACK_WHITE_WALLPAPER_BASED_ON_THEME_DESC to R.string.setting_set_a_plain_black_white_wallpaper_based_on_theme_desc,
    CClauncherSettingsKeys.SETTING_SHOW_APP_NAMES_IN_SEARCH_RESULTS_AFTER_TYPING_THIS_MANY_CHARACTERS_SET_TO_0_TO_USE_THE_SHOW_APP_NAMES_SETTING_INSTEAD_DESC to R.string.setting_show_app_names_in_search_results_after_typing_this_many_characters_set_to_0_to_use_the_show_app_names_setting_instead_desc,
    CClauncherSettingsKeys.SETTING_SHOW_PAGE_DOTS_AT_THE_BOTTOM_OF_THE_HOME_SCREEN_DESC to R.string.setting_show_page_dots_at_the_bottom_of_the_home_screen_desc,
    CClauncherSettingsKeys.SETTING_SHOW_SEARCH_WEB_BUTTON_WHEN_NO_APPS_MATCH_DESC to R.string.setting_show_search_web_button_when_no_apps_match_desc,
    CClauncherSettingsKeys.SETTING_USE_THE_SAME_FONT_SIZE_FOR_SEARCH_RESULTS_AS_HOME_SCREEN_DESC to R.string.setting_use_the_same_font_size_for_search_results_as_home_screen_desc,
    CClauncherSettingsKeys.SETTING_WHEN_DISABLED_TAPPING_AN_APP_DRAWER_APP_DOES_NOTHING_LONG_PRESS_STILL_OPENS_THE_MENU_DESC to R.string.setting_when_disabled_tapping_an_app_drawer_app_does_nothing_long_press_still_opens_the_menu_desc,
    CClauncherSettingsKeys.SETTING_APPLABELALIGNMENT_OPTIONS to R.array.setting_app_label_alignment_options,
    CClauncherSettingsKeys.SETTING_APPTHEME_OPTIONS to R.array.setting_apptheme_options,
    CClauncherSettingsKeys.SETTING_DEFAULTSCREEN_OPTIONS to R.array.setting_defaultscreen_options,
    CClauncherSettingsKeys.SETTING_FONTWEIGHT_OPTIONS to R.array.setting_fontweight_options,
    CClauncherSettingsKeys.SETTING_ITEMSPACING_OPTIONS to R.array.setting_item_spacing_options,
    CClauncherSettingsKeys.SETTING_SCREENORIENTATION_OPTIONS to R.array.setting_screenorientation_options,
    CClauncherSettingsKeys.SETTING_SEARCHALIASESMODE_OPTIONS to R.array.setting_searchaliasesmode_options,
    CClauncherSettingsKeys.SETTING_SEARCHBARPOSITION_OPTIONS to R.array.setting_search_bar_position_options,
    CClauncherSettingsKeys.SETTING_SEARCHRESULTSALIGNMENT_OPTIONS to R.array.setting_search_results_alignment_options,
    CClauncherSettingsKeys.SETTING_SEARCHSORTORDER_OPTIONS to R.array.setting_searchsortorder_options,
    CClauncherSettingsKeys.SETTING_SEARCHTYPE_OPTIONS to R.array.setting_searchtype_options,
    CClauncherSettingsKeys.SETTING_SWIPEDOWNACTION_OPTIONS to R.array.setting_swipedownaction_options,
    CClauncherSettingsKeys.SETTING_SWIPELEFTACTION_OPTIONS to R.array.setting_swipeleftaction_options,
    CClauncherSettingsKeys.SETTING_SWIPERIGHTACTION_OPTIONS to R.array.setting_swiperightaction_options,
    CClauncherSettingsKeys.SETTING_SWIPEUPACTION_OPTIONS to R.array.setting_swipeupaction_options,
)

fun ccLauncherStringResourceProvider(context: Context): StringResourceProvider =
    AndroidStringResourceProvider(context) { key -> settingsResources[key] ?: 0 }
